### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by class101** [horsicq/XArchive#2]
DIE do not build anymore on Arch Linux

https://github.com/horsicq/XArchive/blob/427347deff432d22081b68e5551ad90d2440c03d/xsevenzip.cpp#L468
https://github.com/horsicq/XArchive/blob/427347deff432d22081b68e5551ad90d2440c03d/xsevenzip.cpp#L493
```
/qt/QtScriptTools -I/usr/include/qt/QtScript -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o xcab.o ../../XArchive/xcab.cpp
../../XArchive/xsevenzip.cpp: In member function ‘qint32 XSevenZip::getXRecord(XBinary::_MEMORY_MAP*, qint64, XSevenZip::XRECORD*, qint64)’:
../../XArchive/xsevenzip.cpp:493:19: error: format not a string literal and no format arguments [-Werror=format-security]
  493 |             qDebug(_sTest.toLatin1().data());
```
Haven't checked if they are all causing build error but as Arch Linux defaults to `-Wformat -Werror=format-security` this would be good practice you add also this flag to your build. For infos the all the default are `/etc/makepkg.conf`

```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
```

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! 

Fixed: https://github.com/horsicq/XArchive/commit/5b0bc10ef37d20cd7ef30c3890f8579034f31331

I added **-Werror=format-security** to all my projects
